name: 💡 Feature Request
description: Suggest a new idea or feature for Laravel TDDraft
title: "[Feature] <Your short title here>"
labels: [type:feature]
body:

  - type: dropdown
    id: area
    attributes:
      label: Area / Component
      description: Which part of the codebase is affected?
      options:
        - commands
        - tests
        - docs
        - config
        - cli
        - internal
    validations:
      required: true

  - type: textarea
    id: need
    attributes:
      label: What problem does this feature solve?
      placeholder: |
        Describe the pain point or need you're trying to address.
        Example: "Currently there's no support for test promotion..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe your proposed solution
      placeholder: |
        How would you implement this feature? Include examples or expected command syntax if possible.
    validations:
      required: true
